AREAS: dict[str, str] = {
    "Barking, Havering and Redbridge University Hospitals": "https://www.swiftqueue.co.uk/bhr.php",
    "Buckinghamshire Healthcare NHS Trust": "https://www.swiftqueue.co.uk/buckinghamshire.php",
    "Coventry and Warwickshire Blood Tests": "https://www.swiftqueue.co.uk/uhcw.php?group=Coventry_adult",
    "East London NHS Phlebotomy Clinics": "https://www.swiftqueue.co.uk/elft.php",
    "East Sussex Phlebotomy": "https://www.swiftqueue.co.uk/east_sussex_phlebotomy.php",
    "Frimley Health NHS Foundation Trust Bloods": "https://www.swiftqueue.co.uk/fhftpaeds.php",
    "Hertfordshire Community NHS Trust": "https://www.swiftqueue.co.uk/hertfordshire.php?group=HertF_Adult",
    "Homerton Healthcare NHS Foundation Trust": "https://www.swiftqueue.co.uk/homerton.php",
    "Lewisham and Greenwich NHS Trust": "https://www.swiftqueue.co.uk/lewisham.php",
    "Medway Phlebotomy Network": "https://www.swiftqueue.co.uk/medway.php",
    "Mid Essex Phlebotomy Network": "https://www.swiftqueue.co.uk/midessex.php",
    "NELFT Barking, Dagenham, Havering and Redbridge": "https://www.swiftqueue.co.uk/nelft-bhr.php",
    "NELFT Waltham Forest Phlebotomy": "https://www.swiftqueue.co.uk/nelft.php",
    "Newham University Hospital Phlebotomy": "https://www.swiftqueue.co.uk/NUH_Phlebotomy.php",
    "North Middlesex University Hospital Blood Tests": "https://www.swiftqueue.co.uk/northmid_opd.php",
    "North Warwickshire Blood Test Clinics": "https://www.swiftqueue.co.uk/gehall.php",
    "Northampton General Hospital Network": "https://www.swiftqueue.co.uk/northampton.php",
    "Pathology First Blood Test Clinic Network": "https://www.swiftqueue.co.uk/ippmain.php",
    "Plymouth Adult Blood Test": "https://www.swiftqueue.co.uk/plymouth_adult_blood_test.php",
    "Princess Alexandra Hospital, Harlow": "https://www.swiftqueue.co.uk/pah.php?group=PAH_Adult",
    "Royal Berkshire Blood Tests": "https://www.swiftqueue.co.uk/royal_berkshire.php",
    "Royal Free London NHS Foundation Trust": "https://www.swiftqueue.co.uk/royalfree.php",
    "Royal Surrey Hospital NHS Foundation Trust": "https://www.swiftqueue.co.uk/royalsurrey.php?group=RoyalSurrey_Adult",
    "Surrey and Sussex Healthcare NHS Trust": "https://www.swiftqueue.co.uk/surreyandsussex.php",
    "Synnovis GP Referral (King's, Guy's & St Thomas')": "https://www.swiftqueue.co.uk/synnovis.php?group=Syn_GP",
    "Synnovis Outpatient Phlebotomy (King's, Guy's & St Thomas')": "https://www.swiftqueue.co.uk/synnovis.php?group=Syn_OP",
    "University College London Hospitals": "https://www.swiftqueue.co.uk/UCLH_CC.php",
    "University Hospitals of Derby and Burton": "https://www.swiftqueue.co.uk/uhdb.php",
    "West Hertfordshire Teaching Hospitals": "https://www.swiftqueue.co.uk/wherts.php?group=Wherts_Adult",
    "West Suffolk NHS": "https://www.swiftqueue.co.uk/west_suffolk.php",
    "Whittington Health NHS Trust": "https://www.swiftqueue.co.uk/whittington.php?group=WHIT_GP",
    "Wrightington, Wigan and Leigh NHS Phlebotomy Clinics": "https://www.swiftqueue.co.uk/wigan.php",
}
